os: osx
language: node_js
node_js:
  - "node"
stages:
  - compile
  - name: deploy-dmg
    if: tag IS present
  - name: deploy-web
    if: branch = master
jobs:
  include:
    - stage: compile
      script:
        - xcodebuild -project atemOSC/atemOSC.xcodeproj -target AtemOSC

    - stage: deploy-dmg
      install: npm install --global create-dmg
      script: bash .travis/deploy.sh
      deploy:
        - provider: releases
          edge: true
          token: $GITHUB_TOKEN
          file: output/*
          draft: true
          overwrite: true
          on:
            tags: true

    - stage: deploy-web
      script: echo "Deploying to Github Pages"
      deploy:
        - provider: pages
          local_dir: website
          token: $GITHUB_TOKEN
          on:
            branch: master
