os: osx
language: node_js
node_js:
  - "node"
stages:
  - compile
  - deploy-dmg
  - name: deploy-dmg
    if: type IN (push) AND branch = master
  - deploy-web
jobs:
  include:
    - stage: compile
      script:
       - echo "Before"
       - echo $TRAVIS_TAG
       - echo "After"
       - xcodebuild -project atemOSC/atemOSC.xcodeproj -target AtemOSC
    - stage: deploy-dmg
      env:
        - TAG_NUMBER=$( echo $TRAVIS_TAG | sed 's/[^0-9.]*//g' )
        - PREVIOUS_TAG=$( git describe --abbrev=0 --tags )
      install: npm install --global create-dmg
      script:

        # Only continue if a tag is set for this commit and is different from last tag
        - if [ -z ${TRAVIS_TAG+x} ] && [ "$TRAVIS_TAG" -ne "$PREVIOUS_TAG" ]; then return 1; else return 0; fi

        # Update the version of the binary to match the tag
        - /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $TAG_NUMBER" atemOSC/atemOSC-Info.plist

        # Build the new binary and sign
        - xcodebuild -project atemOSC/atemOSC.xcodeproj -target AtemOSC
        - ./.travis/sign.sh

        # Create and validate the DMG
        - create-dmg atemOSC/build/Releases/atemOSC.app
        - echo "$(find atemOSC-*.dmg)"
        - find atemOSC-*.dmg

      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: atemOSC-*.dmg
          skip_cleanup: true
          on:
            tags: true
    - stage: deploy-web
      deploy:
        - provider: pages
          local_dir: website
          github_token: $GITHUB_TOKEN
          on:
            branch: master
