os: osx
language: node_js
node_js:
  - "node"
stages:
  - compile
  - deploy-dmg
#  - name: deploy-dmg
#    if: type IN (push) AND branch = master
  - deploy-web
jobs:
  include:
    - stage: compile
      script:
       - xcodebuild -project atemOSC/atemOSC.xcodeproj -target AtemOSC
    - stage: deploy-dmg
      install: npm install --global create-dmg
      script:
# - xcodebuild -project atemOSC/atemOSC.xcodeproj -target AtemOSC
        - ./.travis/sign.sh
        - create-dmg atemOSC/build/Releases/atemOSC.app
        - echo "$(find atemOSC-*.dmg)"
        - find atemOSC-*.dmg
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: atemOSC-*.dmg
          skip_cleanup: true
          on:
            tags: true
    - stage: deploy-web
      deploy:
        - provider: pages
          local_dir: website
          github_token: $GITHUB_TOKEN
          on:
            branch: master
